---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - automation
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all" # Also indirect dependencies.
    groups:
      elastic-apm:
        patterns:
          - "go.elastic.co/apm/*"
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
  - package-ecosystem: "gomod"
    directory: "/cmd/distribution"
    schedule:
      interval: "daily"
    labels:
      - automation
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all" # Also indirect dependencies.
