queue_rules:
  - name: default
    merge_method: squash
    conditions:
      - check-success=buildkite/package-registry

pull_request_rules:
  - name: automatic approval for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
  - name: automatic merge of bot 🤖
    conditions:
      - check-success=buildkite/package-registry
      - check-success=CLA
      - approved-reviews-by=@elastic/ecosystem
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        name: default
