---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-package-registry
  description: Buildkite Pipeline for the Package Registry project
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/package-registry

spec:
  type: buildkite-pipeline
  owner: group:ingest-fp
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: package-registry
      description: Buildkite Pipeline for the Package Registry project
    spec:
      repository: elastic/package-registry
      pipeline_file: ".buildkite/pipeline.yml"
      provider_settings:
        build_pull_request_forks: false
        build_pull_requests: true
      teams:
        ecosystem: {}
        ingest-fp:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: package-registry
  description: package-registry - Elastic Package Registry

spec:
  type: tool
  owner: group:ingest-fp
  system: platform-ingest
  lifecycle: production
