# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_MAGE_VERSION: '1.14.0'

steps:
  - label: "Checks formatting / linting"
    command:
      - "mage -debug check"
    agents:
      image: "golang:1.20.3"
      cpu: "8"
      memory: "4G"
