# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_MAGE_VERSION: '1.14.0'

steps:
  - label: "Checks formatting / linting"
    command:
      - "./pre-install-command.sh 'mage -debug check'"
    agents:
      image: "golang:1.20.3"
      cpu: "8"
      memory: "4G"

  - label: "Build"
    command:
      - "./pre-install-command.sh 'mage -debug build'"
    agents:
      image: "golang:1.20.3"
      cpu: "8"
      memory: "4G"

  - label: "Test on Linux"
    command:
      - "./pre-install-command.sh 'mage -debug test'|tee tests-report.txt"
      - ls
    agents:
      image: "golang:1.20.3"
      cpu: "8"
      memory: "4G"

  - label: "Test on Windows"
    command:
      - "choco --version"
    agents:
      provider: "gcp"
      image: "family/ci-windows-2022"
