# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_MAGE_VERSION: '1.14.0'
  SETUP_GOLANG_VERSION: '1.20.4'

steps:
  - label: "Checks formatting / linting"
    command:
      - ".buildkite/scripts/pre-install-command.sh 'mage -debug check'"
    agents:
      image: "golang:${SETUP_GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"

  - label: "Build"
    command:
      - ".buildkite/scripts/pre-install-command.sh 'mage -debug build'"
    agents:
      image: "golang:${SETUP_GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"

  - label: "Test on Linux"
    command:
      - ".buildkite/scripts/pre-install-command.sh 'mage -debug test'|tee tests-report-linux.txt"
      - go install github.com/jstemmer/go-junit-report/v2@latest && go-junit-report > tests-report-linux.xml < tests-report-linux.txt
    agents:
      image: "golang:${SETUP_GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"
    artifact_paths:
      - "tests-report-linux.txt"

  - label: "Test on Windows"
    command:
      - ".buildkite/scripts/pre-install-command.ps1"
    agents:
      provider: "gcp"
      image: "family/ci-windows-2022"
    artifact_paths:
      - "tests-report-win.xml"
