# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_GVM_VERSION: 'v0.6.0' # https://github.com/andrewkroh/gvm/issues/44#issuecomment-1013231151
  SETUP_MAGE_VERSION: '1.15.0'
  JQ_VERSION: '1.7'
  DOCKER_IMG: "docker.elastic.co/package-registry/package-registry"
  DOCKER_IMG_PR: "docker.elastic.co/observability-ci/package-registry"
  # Agent images used in pipeline steps
  LINUX_GOLANG_AGENT_IMAGE: "golang:${SETUP_GOLANG_VERSION}"
  WINDOWS_AGENT_IMAGE: "family/core-windows-2022"
  MACOS_ARM_AGENT_IMAGE: "generic-13-ventura-arm"

steps:
  - label: ":golangci-lint: Checks formatting / linting"
    key: lint
    command:
      - ".buildkite/scripts/lint.sh"
    agents:
      image: "${LINUX_GOLANG_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"

  - label: ":hammer: Build"
    key: build
    command:
      - ".buildkite/scripts/build.sh"
    agents:
      image: "${LINUX_GOLANG_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"

  - label: ":wrench: Smoke tests running EPR with fake GCS server"
    key: smoke-test-fake-gcs-server
    command:
      - ".buildkite/scripts/test-epr-gcs.sh"
    agents:
      provider: "gcp"

  - group: ":go: Run Unit tests"
    key: unit-tests
    steps:
      - label: ":linux: Test on Linux"
        key: test-linux
        command:
          - ".buildkite/scripts/run-tests.sh"
        agents:
          image: "${LINUX_GOLANG_AGENT_IMAGE}"
          cpu: "8"
          memory: "4G"
        artifact_paths:
          - "tests-report-linux.xml"

      - label: ":windows: Test on Windows"
        key: test-win
        command:
          - ".buildkite/scripts/run-tests.ps1"
        agents:
          provider: "gcp"
          image: "${WINDOWS_AGENT_IMAGE}"
        artifact_paths:
          - "tests-report-win.xml"

      - label: ":macos: Test on Macos ARM"
        key: test-macos-arm
        command:
          - ".buildkite/scripts/run-tests.sh"
        agents:
          provider: "orka"
          imagePrefix: "${MACOS_ARM_AGENT_IMAGE}"
        artifact_paths:
          - "tests-report-darwin.xml"

  - group: ":lock: Run FIPS Unit tests"
    key: fips-tests
    steps:
      - label: ":linux::lock: FIPS Test on Linux"
        key: test-fips-linux
        command:
          - ".buildkite/scripts/run-tests-fips.sh"
        agents:
          image: "${LINUX_GOLANG_AGENT_IMAGE}"
          cpu: "8"
          memory: "4G"
        artifact_paths:
          - "tests-report-fips-linux.xml"

      - label: ":macos::lock: FIPS Test on Macos ARM"
        key: test-fips-macos-arm
        command:
          - ".buildkite/scripts/run-tests-fips.sh"
        agents:
          provider: "orka"
          imagePrefix: "${MACOS_ARM_AGENT_IMAGE}"
        artifact_paths:
          - "tests-report-fips-darwin.xml"

  - label: ":junit: Junit annotate"
    agents:
      # requires at least "bash", "curl" and "git"
      image: "docker.elastic.co/ci-agent-images/buildkite-junit-annotate:1.0"
    plugins:
      - junit-annotate#v2.7.0:
          artifacts: "tests-report-*.xml"
          fail-build-on-error: true
          report-skipped: true
          always-annotate: true
          run-in-docker: false
    depends_on:
      - step: "test-linux"
        allow_failure: true
      - step: "test-win"
        allow_failure: true
      - step: "test-macos-arm"
        allow_failure: true
      - step: "test-fips-linux"
        allow_failure: true
      - step: "test-fips-macos-arm"
        allow_failure: true

  - label: ":docker: Publish docker image"
    key: "publish"
    command: ".buildkite/scripts/publish.sh"
    agents:
      provider: "gcp"
    depends_on:
      - step: "test-linux"
        allow_failure: false
      - step: "test-win"
        allow_failure: false
      - step: "test-macos-arm"
        allow_failure: false
      - step: "test-fips-linux"
        allow_failure: false
      - step: "test-fips-macos-arm"
        allow_failure: false
      - step: "build"
        allow_failure: false
      - step: "lint"
        allow_failure: false
      - step: "smoke-test-fake-gcs-server"
        allow_failure: false
    plugins:
      - elastic/vault-docker-login#v0.6.0:
          secret_path: 'kv/ci-shared/platform-ingest/elastic_docker_registry'

  - trigger: "package-storage-infra-update-package-registry"
    label: ":esbuild: Downstream - Update package registry"
    key: "downstream-update-package-registry"
    async: true
    build:
      branch: "main"
      env:
        DRY_RUN: "false"
        DRAFT_PR: "false"
        EPR_VERSION: "${BUILDKITE_TAG}"
    depends_on:
      - step: "publish"
        allow_failure: false
    if: build.tag =~ /^v\d+\.\d+\.\d+$$/
