# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_MAGE_VERSION: '1.14.0'
  SETUP_GOLANG_VERSION: '1.20.4'
  DOCKER_REGISTRY: 'docker.elastic.co'
  DOCKER_IMG: "${DOCKER_REGISTRY}/package-registry/temp-package-registry" # TODO needs to rename after tests: remove prefix temp
  DOCKER_IMG_PR: "${DOCKER_REGISTRY}/observability-ci/temp-package-registry" # TODO needs to rename after tests: remove prefix temp

steps:
  - label: ":golangci-lint: Checks formatting / linting"
    command:
      - ".buildkite/scripts/lint.sh"
    agents:
      image: "golang:${SETUP_GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"

  - label: ":hammer: Build"
    command:
      - ".buildkite/scripts/build.sh"
    agents:
      image: "golang:${SETUP_GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"

  - label: ":linux: Test on Linux"
    key: test-linux
    command:
      - ".buildkite/scripts/run-tests.sh"
    agents:
      image: "golang:${SETUP_GOLANG_VERSION}"
      cpu: "8"
      memory: "4G"
    artifact_paths:
      - "tests-report-linux.xml"

  - label: ":junit: Junit annotate"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "tests-report-*.xml"
    agents:
      provider: "gcp" #junit plugin requires docker
    depends_on:
      - step: "test-linux"
        allow_failure: true

  - label: "Publish docker image"
    key: "publish"
    command: ".buildkite/scripts/publish.sh"
    agents:
      provider: "gcp"
    depends_on:
      - step: "test-linux"
        allow_failure: false
