# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_GOLANG_VERSION: '1.20.4'
  DOCKER_REGISTRY: 'docker.elastic.co'

steps:
  - input: "Input version for docker tag"
    key: input
    if: build.source == 'trigger_job'
    fields:
      - text: "The docker tag to be published (format: major.minor.patch(-prerelease)?)."
        hint: "e.g. 0.0.1"
        key: "DOCKER_TAG"
        required: true
        default: "latest"

  - label: ":hammer: Validate docker tag"
    if: build.source == 'trigger_job'
    key: validate
    command:
      - ".buildkite/scripts/validate-tag.sh"
    depends_on:
      - step: "input"
        allow_failure: false

  - label: ":hammer: Release registry distribution {{matrix.tag_name}}"
    if: build.source == 'trigger_job'
    matrix:
      setup:
        tag_name:
          - "lite"
          - "production"
    env:
      TAG_NAME: "{{matrix.tag_name}}"
      DRY_RUN: true
    command:
      - ".buildkite/scripts/publish-distribution.sh"
    agents:
      provider: "gcp"
    depends_on:
      - step: "validate"
        allow_failure: false
